### PR TITLE
Split out Requires and BuildRequires for legibility

### PR DESCRIPTION
**Pull request by nkadel**
There are two changes here. One is to add a ".gitignore", to ignore editing temp files and to ignore git checked out "awx" or "awx-logos".

The other is to split out the "Requires:" and "BuildRequires:" lines into individual lines for each requirement, which is the Fedora and RHEL standard upstream and is vastly more legible. It's especially more legible when an individual element is added or updated.

### CODE REVIEW

**Comment by MrMEEE** [comment]
Hi

Thanks for the PR..

What is the reason to have awx/ and awx-logs/ in gitignore???

**Comment by nkadel** [comment]
In case of checking out those repos, locally, to build up the Source tarballs.

**Comment by MrMEEE** [comment]
But why would you do this in the same folder?

**Comment by nkadel** [comment]
To script publishing the tarball into the docket container fro RPM building. I don’t insist on those .gitignore lines.

I was looking at that complex “script-build a docker image”, which requires local root privileges, and thinking “can I do this gracefully with ‘mock’”? That means getting the awx tarball. Since the github repo does not have published tarballs, this is space to grab the repo and use git archive to generate tarballs.

I don’t insist on it, just looking at an approach.

**Comment by MrMEEE** [comment]
I don't use any of the scripts in here.. Only the sources for the RPM...

**Comment by VJoshi0** [comment]
Hello, I have offline VMs where I need to build AWX. As listed above I saw about 160 rh-python36-* dependencies. Where I can find a tar ball or list of all python rpms I need for AWX? I want to build HA AWX based on https://github.com/MrMEEE/awx-build/issues/26. 
Not using docker, plan to use RHEL7 VMs to create HA.
But I'm lost to collect all rh-python36-* , will appreciate if I know what order which package need to get installed. Thanks.

**Comment by nkadel** [comment]
I’d expect to see the relevant yum repos configured in the Dockerfiles? Where are those?

Sent from my iPhone

**Comment by MrMEEE** [comment]
@VJoshi0 You can get the SRPMS here:
https://awx.wiki/dependencies-srpms/
Also, if you just want the rpms they are here:
https://awx.wiki/dependencies-rpms/

Right now, the dependencies are something that definitely needs a cleanup... 

In the https://github.com/ansible/awx/tree/devel/requirements txt-files you should be able to see which are needed, and which are deprecated...

I would love to have the time to clean it up, but realisticly, I think it will only happen when I move to Streams/Modules in CentOS8

**Pull request merged**
